//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.07 at 02:11:29 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://fabthechemist.net/courses", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.fabthechemist.courses;
